### ISSUE TITLE
habitatFor interaction - is this similar to epihyte of

### ISSUE THREAD

**Issue by jhpoelen** [diatomsRcool/greenland_interactions#3]
Hey Anne - 
Just noticed your records that indicate evidence for that some crabs use seaweed as a habitat. Is this interaction type "habitatFor" similar  epiphyte of http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0008501 ?

I've had a similar discussion around habitats for vampire moths with @seltmann and @pbuttigieg in https://github.com/seltmann/vampire-moth-globi/issues/2#issuecomment-423831903 . Perhaps they have some ideas on how to model this biotic interaction.

**Comment by diatomsRcool** [comment]
No. This means that there are seaweeds and the crabs live among them. 
Does that make sense? The seaweed isn't an epiphyte of the crab.

**Comment by jhpoelen** [comment]
Yep, that makes sense. I was trying to find a existing term that might fit, and from what you are saying, an epiphyte interaction does not apply in this case. Perhaps some of your biology colleagues have some ideas on the topic.

**Comment by pbuttigieg** [comment]
Perhaps worth checking out how we handle habitat in ENVO to prevent it
getting mixed up with other environmental semantics.


We would say that link the crab to a "crab habitat " and the habitat class overlaps seaweed
etc. By treating a species habitat itself as a class, we don't force the crab itself (at the class level) into an environmental association it may not encounter in it's life.


The 2016 ENVO paper goes into this a bit. Seems fussy, but circumvents some considerable weirdness.

**Comment by diatomsRcool** [comment]
Totally agree, but does that semantics need to be held within GloBI?

**Comment by jhpoelen** [comment]
(apologies for the delay) I'd say that the context in which an interaction occurs is relevant to GloBI, just like the location, time and participating organisms are. GloBI already has the concept of a habitat but the data is not yet exposed in a meaningful way. 

So, the claim that "a crab ate a sea horse in the sea grass" can be captured, assuming that the sea grass is labeled as a habitatName is some column separate from the interactionTypeName .
